### ISSUE TITLE
ship

### ISSUE THREAD

**Issue by jufashpfy** [jufa/starfleet_generator#20]
{
  "nacelle_toggle": false,
  "nacelle_y": 24.96,
  "nacelle_x": 0,
  "nacelle_z": -12.69,
  "nacelle_length": 7.99,
  "nacelle_radius": 0.61,
  "nacelle_widthRatio": 1.12,
  "nacelle_rotation": 0,
  "nacelleLower_toggle": true,
  "nacelleLower_y": 21.71,
  "nacelleLower_x": 4.44,
  "nacelleLower_z": 8.68,
  "nacelleLower_length": 28.19,
  "nacelleLower_radius": 1.5,
  "nacelleLower_widthRatio": 1.02,
  "nacelleLower_rotation": -0.46,
  "engineering_toggle": true,
  "engineering_y": -24.8,
  "engineering_z": 3.89,
  "engineering_length": 16.7,
  "engineering_radius": 2.03,
  "engineering_widthRatio": 0.98,
  "engineering_skew": -0.71,
  "pylon_toggle": false,
  "pylon_nacelleForeOffset": 0.25,
  "pylon_nacelleAftOffset": 0.2,
  "pylon_engineeringForeOffset": 0.26,
  "pylon_engineeringAftOffset": 0.1,
  "pylon_thickness": 0.17,
  "pylonLower_toggle": true,
  "pylonLower_nacelleForeOffset": 0.21,
  "pylonLower_nacelleAftOffset": 0.68,
  "pylonLower_engineeringForeOffset": 0.25,
  "pylonLower_engineeringAftOffset": 0.11,
  "pylonLower_thickness": 0.34,
  "neck_toggle": true,
  "neck_primaryForeOffset": 0.39,
  "neck_primaryAftOffset": 0,
  "neck_engineeringForeOffset": 0.36,
  "neck_engineeringAftOffset": 0.08,
  "neck_thickness": 0.42,
  "primary_toggle": true,
  "primary_y": 0.71,
  "primary_z": -2.91,
  "primary_radius": 15.98,
  "primary_thickness": 4.54,
  "primary_widthRatio": 0.56,
  "name": "USMC Taildragger",
  "nacelle_lowerToggle": false,
  "neckThickness": 1.08
}

**Comment by jufa** [comment]
implemented
